# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
contact_links:
  - name: Vespa.ai support
    url: https://vespa.ai/support
    about: Find resources like a FAQ, use cases, Stack Overflow and live chats to help resolve your issue
